### ISSUE TITLE
blocks-layout not loading blocks-loader in latest build

### ISSUE THREAD

**Issue by humancompanion** [EightShapes/Blocks#116]
blocks-layout, which is not actually checked in here (ahem) but we'll handle bugs for here anyway, failed to load blocks-loader. I wasn't able to ascertain why. However, the fix was to change this:

````
 if (autoload === true) {
    $(window).on('load', function () {
      $('body').BlocksLoader();
    });
  }
````

to this:

````
if (autoload === true) {
  $('body').BlocksLoader();
}
````

Perhaps the load event has already fired by the time blocks-loader is inserted into the <head>?

**Comment by kevinmpowell** [comment]
The latest version: v2.3.7 appears to be working fine with blocks-layout
