### ISSUE TITLE
Add support for data-enclose back into Loader

### ISSUE THREAD

**Issue by humancompanion** [EightShapes/Blocks#117]
I removed support for data-enclose because I didn't want to add underscore back in as a dependency. lodash is a good replacement and we can potentially just grab the ~4 functions we need. However, the jspm loader is failing to load lodash. Thus to unblock the move to ES6 I'm breaking this out into a distinct bug.

The error is: "Module process not declared as a dependency"
It is in fact declared as a dependency. I tired a bunch of different things but, to no avail. So for now this feature remains unsupported.

**Comment by kevinmpowell** [comment]
Closing this issue since **Include** functionality is in flux
