### ISSUE TITLE
Toolbar not displaying when using versione 2.5.1

### ISSUE THREAD

**Issue by robmaggidev** [EightShapes/Blocks#134]
Hello, not sure if it's an issue but I don't know where else to ask about it.
I'm using version 2.5.1 but I can't see the Blocks admin toolbar, with component's markers and all the stuff that I had a couple of years ago when there was the version with the xml config file.
Where can I find docs or support about this new version? Is there a forum, a googlegroup or something?
Thanks.

**Comment by humancompanion** [comment]
Rob - Blocks v2 pared Blocks down to mostly the loader and then added some functionality by making each variation a template that can be data driven. The documentation is a bit sparse but, the wiki of this repo is the place to look: https://github.com/EightShapes/Blocks/wiki

**Comment by robmaggidev** [comment]
Thanks for the quick reply, now I understand! So basically you chose to abandon the "team design" side (annotations, etc.) to have the core mechanism you need for prototyping. Is it correct?

**Comment by humancompanion** [comment]
The v1 code became difficult to maintain. We've done quite a bit as of late to break the code up into modules. You may see some of the v1 functionality return in the future.

**Comment by nathanacurtis** [comment]
@robmaggidev,

We did refocus on optimizing and expanding the capabilities for modular loading and asset management. That said, many of our client projects require other annotating features – notes next to pages, showing grids of pages together, responsive viewers, etc – and we've begun to build those out. We may or may not deploy those publicly.

Thanks for your interest,

Nathan

**Comment by robmaggidev** [comment]
Thank you guys. I think your vision is pretty good and I believe that Blocks is a great tool also without all the backend functionalities, I haven't use it in a while and I missed it. Happy to discover that you're going further, so thanks for what you're doing for all us ia/ux designers!

**Comment by kevinmpowell** [comment]
Closing this issue for now.
