### ISSUE TITLE
Mark MVP Estimation

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/Blocks#140]
Build features enabling one to mark components within a page, including:

* Mark with label denoted as property in markup
* Automate marking with loader
* Automate marker labeling from loader component file names
* Enable linking marker to documentation page URL
* Link marker to a destination
* Hover marker produces outline
* Customize component outline size (weight), type (dashed? solid?), and color
* Clickable toggle of component overlay via semitransparent color
* Customize overlay color and opacity
* Keyboard shortcut to turn markers on and off in browser (CMD SHIFT M)

![image](https://cloud.githubusercontent.com/assets/1165904/8082881/b748ef76-0f4e-11e5-9558-3cac086ebd80.png)

**Comment by kevinmpowell** [comment]
* Mark would be a separate "Product" in the Blocks Toolkit
* Usable **without** Component Loader if desired (ability to add markers to raw HTML)
* Component Loader could gain a data-attribute allowing it to have Markers auto-generated
* Mark would need to run after Component Loader so it can find all elements that need to be "marked"

**Implementation**
* Essentially a set of data-attributes that can be added to any element that are then used as hooks by a JavaScript file to create and toggle the Mark

** Difficulties **
* How to mark elements differently depending on CSS `display` values: block, inline, inline-block
* Minimum size for mark? What if mark is larger than element being Marked? How to display?


**Issues Breakdown**
* Mark MVP - Standalone, no Component Loader Integration
 * Creating spec / Reviewing -  **3 hours** - Includes review with @humancompanion and @nathanacurtis 
 * Implementation of MVP -  **8 hours**
* Integration with Component Loader
 * Creating spec / Reviewing - **3 hours** - Includes review with @humancompanion and @nathanacurtis 
 * Implementation of CL Integration - **8 hours**

Total: **22 hours**

**Comment by nathanacurtis** [comment]
Design considerations, for our brainstorming:
(available in ```/Users/nathan/Dropbox (EightShapes)/8S Blocks/Wireframes```)

![image](https://cloud.githubusercontent.com/assets/1165904/8230576/8f548d94-158f-11e5-9ec8-b63e324aa0f2.png)

**Comment by nathanacurtis** [comment]
Updated visual feature grid:
![image](https://cloud.githubusercontent.com/assets/1165904/8232380/2eb35098-159d-11e5-9722-fe81ccb8953b.png)

**Comment by kevinmpowell** [comment]
@nathanacurtis any decision on shape of the Mark label? (the 4th row in your grid)

**Comment by nathanacurtis** [comment]
By default, choose the rounded corners of the far left version, consistent with our logo mark. No direction/pointer. Approximate a rounded size consistent with the logo mark, probably 3px or 4px.
