### ISSUE TITLE
Update iconography for Page Framer dimensions annotation

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#154]
https://www.dropbox.com/sh/r6gpdvgo2hxt612/AAAmGrRgkpfHY3k3dgS_92xia?dl=0

![pasted_image_at_2015_06_10_11_27_am](https://cloud.githubusercontent.com/assets/979463/8086714/6e303e8a-0f5c-11e5-830d-ca3c34d6fc3e.png)

* If not scaled, omit scale.
* If scaled by other means (fit within a containing div, or be ###px wide), then convert into calculated scale and show as %.
* Always show viewport height and width, in px

**Comment by nathanacurtis** [comment]
Updated requirements as bullets.

**Comment by kevinmpowell** [comment]
> If scaled by other means (fit within a containing div, or be ###px wide), then convert into calculated scale and show as %.

Currently the Framers all have a fixed width, so this would come into play when we add fluid options. Do you want me to add making the Framer fluid as a separate issue for this Milestone?

**Comment by nathanacurtis** [comment]
Yes, handling fluidity is for another day. For what sizing options we
support today, convert them into scale % for this display.

On Wed, Jun 10, 2015 at 12:34 PM, Kevin Powell <notifications@github.com>
wrote:

> If scaled by other means (fit within a containing div, or be ###px wide),
> then convert into calculated scale and show as %.
>
> Currently the Framers all have a fixed width, so this would come into play
> when we add fluid options. Do you want me to add making the Framer fluid as
> a separate issue for this Milestone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EightShapes/Blocks/issues/154#issuecomment-110824887>.
>



-- 

*Nathan Curtis*
Principal, EightShapes LLC
nathan@eightshapes.com
@nathanacurtis
703-296-8831
