### ISSUE TITLE
Allow data-esb-page-framer attribute to be set at all config levels

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#159]
Use case for on-page config:

    <div data-esb-page-framer-config data-esb-page-framer="http://example.com">
        <div data-esb-viewport-width="320"></div>
        <div data-esb-viewport-width="768"></div>
        <div data-esb-viewport-width="1400"></div>
    </div>

**Comment by nathanacurtis** [comment]
Can you be more descriptive of this issue? I'm not sure what the benefit / gain / feature is.

**Comment by kevinmpowell** [comment]
@nathanacurtis it's just less verbose, basically a syntax shortcut:

@francisrupert's desired syntax:

    <div data-esb-page-framer-config data-esb-page-framer="http://example.com">
        <div data-esb-viewport-width="320"></div>
        <div data-esb-viewport-width="768"></div>
        <div data-esb-viewport-width="1400"></div>
    </div>

vs. current syntax

    <div data-esb-viewport-width="320" data-esb-page-framer="http://example.com"></div>
    <div data-esb-viewport-width="768" data-esb-page-framer="http://example.com"></div>
    <div data-esb-viewport-width="1400" data-esb-page-framer="http://example.com"></div>

**Comment by nathanacurtis** [comment]
If that's the desire, why not just have a esb-viewport-width="320,768,1024"
property on the containing div, without children?

On Thu, Jun 11, 2015 at 11:43 AM, Kevin Powell <notifications@github.com>
wrote:

> @nathanacurtis <https://github.com/nathanacurtis> it's just less verbose,
> basically a syntax shortcut:
>
> @francisrupert <https://github.com/francisrupert>'s desired syntax:
>
> <div data-esb-page-framer-config data-esb-page-framer="http://example.com">
>     <div data-esb-viewport-width="320"></div>
>     <div data-esb-viewport-width="768"></div>
>     <div data-esb-viewport-width="1400"></div>
> </div>
>
> vs. current syntax
>
> <div data-esb-viewport-width="320" data-esb-page-framer="http://example.com"></div>
> <div data-esb-viewport-width="768" data-esb-page-framer="http://example.com"></div>
> <div data-esb-viewport-width="1400" data-esb-page-framer="http://example.com"></div>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EightShapes/Blocks/issues/159#issuecomment-111177761>.
>



-- 

*Nathan Curtis*
Principal, EightShapes LLC
nathan@eightshapes.com
@nathanacurtis
703-296-8831

**Comment by kevinmpowell** [comment]
@nathanacurtis 

> esb-viewport-width="320,768,1024"

Would be a large departure from how it's currently built. @francisrupert's request is in-line with the "one key, one value" method that this and Loader are built around.

If you specified multiple properties as comma-separated values it would require quite a few new rules to be defined for how to resolve all of the properties. 

**Example**
`esb-viewport-width="320,768,1024" esb-overlay="false, true"`   

In the above example does the `overlay="false"` apply to the `320` & `768` framers, or just the `320` framer?

We'd have to pick one or the other and code in that rule. It's a syntactic slippery slope.

Any reason not to implement @francisrupert's suggestion?

**Comment by nathanacurtis** [comment]
No.

On Thu, Jun 11, 2015 at 11:55 AM, Kevin Powell <notifications@github.com>
wrote:

> @nathanacurtis <https://github.com/nathanacurtis>
>
> esb-viewport-width="320,768,1024"
>
> Would be a large departure from how it's currently built. @francisrupert
> <https://github.com/francisrupert>'s request is in-line with the "one
> key, one value" method that this and Loader are built around.
>
> If you specified multiple properties as comma-separated values it would
> require quite a few new rules to be defined for how to resolve all of the
> properties.
>
> *Example*
> esb-viewport-width="320,768,1024" esb-overlay="false, true"
>
> In the above example does the overlay="false" apply to the 320 & 768
> framers, or just the 320 framer?
>
> We'd have to pick one or the other and code in that rule. It's a syntactic
> slippery slope.
>
> Any reason not to implement @francisrupert
> <https://github.com/francisrupert>'s suggestion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EightShapes/Blocks/issues/159#issuecomment-111182459>.
>



-- 

*Nathan Curtis*
Principal, EightShapes LLC
nathan@eightshapes.com
@nathanacurtis
703-296-8831

**Comment by francisrupert** [comment]
Plus it'd be more flexible to have freedom of structure within for whatever reason, e.g...

```html
<div class="foo" data-esb-page-framer-config data-esb-page-framer="http://example.com">
  <div class="foo_bar">
    <div data-esb-viewport-width="320"></div>
  </div>
  <div class="foo_bar">
    <div data-esb-viewport-width="768"></div>
  </div>
  <div class="foo_bar">
    <div data-esb-viewport-width="1400"></div>
  </div>
</div>
```

**Comment by nathanacurtis** [comment]
France,

That's the kind of flexibility that signals lots of other strange
situations. How high can that config be? What if a config is in a config?
What's with all the intervening elements? I'm less comfortable and less
interested in making this thing super-super-flexible.

On Thu, Jun 11, 2015 at 12:07 PM, Francis Rupert <notifications@github.com>
wrote:

> Plus it'd be more flexible to have freedom of structure within for
> whatever reason, e.g...
>
> <div class="foo" data-esb-page-framer-config data-esb-page-framer="http://example.com">
>   <div class="foo_bar">
>     <div data-esb-viewport-width="320"></div>
>   </div>
>   <div class="foo_bar">
>     <div data-esb-viewport-width="768"></div>
>   </div>
>   <div class="foo_bar">
>     <div data-esb-viewport-width="1400"></div>
>   </div>
> </div>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EightShapes/Blocks/issues/159#issuecomment-111187018>.
>



-- 

*Nathan Curtis*
Principal, EightShapes LLC
nathan@eightshapes.com
@nathanacurtis
703-296-8831

**Comment by kevinmpowell** [comment]
> How high can that config be?

A component will find the closest ancestor in the DOM that defines a framer-config and use that ancestor as its "page-level-config"



> What if a config is in a config?

The first one wins.

**Example**
```
<div data-esb-framer-config data-esb-overlay="false" data-scale="0.6">
    <div data-esb-framer-config data-esb-overlay="true">
        <div data-esb-framer="http://example.com"></div>
    </div>  
</div>
```

The Framer in this example will have `overlay="true"` and `data-scale="0.25"` (the default scale value). The code finds the first `data-esb-framer-config` and stops looking further up the DOM. In this example the outermost `data-esc-framer-config` element isn't having any effect on the Framer itself.



> What's with all the intervening elements?

@francisrupert is showing a real-world example of using these within a grid system or any other form of markup. It's nice to be able to define config at some sort of "containing element" and not worry about other elements "in-between" the config and the Framer element itself.
