### ISSUE TITLE
Add additional documentation for dimension options (more examples)

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#160]
* Grokking how data-esb-width, data-esb-height, data-esb-viewport-width, data-esb-viewport-aspect-ratio and data-esb-scale work together (and seemingly against each other sometimes) was biggest hurdle.
* Would love lots of pre-fab examples of most common beyond just "all are same width" next to each other.

**Comment by nathanacurtis** [comment]
Yes, I'd love to see a wider variety of use cases / examples to illustrate the flexibility. Let me know if you need a 15min sketching round for it.
