### ISSUE TITLE
Update CSS Styling section of Framer Wiki

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#161]
1. Add language to CSS Styling that it inherits project's style.
2. Document best path for designers to customize. Any of the below could be a choice a designer makes, but we should provide a recommendation or guidelines on how to do each. 
 * Make SASS file, esb.scss, available and do what they want with it – thus creating their own esb.css. Can esb.scss stand alone? e.g. dependencies, variables, functions, etc.
 * Reference esb.css as is, and create their own CSS modifications in newly created file to include after esb.css? This is most likely scenario, e.g. .esb-page-framer-title { font-size: 14px; }

**Comment by nathanacurtis** [comment]
1. Publish both the SCSS and CSS files, for we shouldn't assume users are going to use our flavor of SCSS.
2. SCSS shouldn't be constrained by standalone. Our SCSS suits our purposes. If a customizer wants to customize it and uses a different flavor of SCSS, then have them replace the CSS.
3. This probably suggests that Blocks (broadly) will need a /base, but this issue of setup shouldn't be constrained by that.

**Comment by kevinmpowell** [comment]
Have an example of what an "override" CSS would look like.
