### ISSUE TITLE
data-viewport-width="iPhone"

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#165]
Device defaults for width & height for a list of common devices.

Maybe a different attribute `data-viewport-device=`

iPhone 4/5/6/plus
iPad
Others

**Comment by francisrupert** [comment]
Related: note how I approximated a "mobile device height" via `data-esb-height="205"`, which got me at `569px` (was aiming for 56**8**). A would-be `data-esb-viewport-height="568"` mayhaps?

**Comment by francisrupert** [comment]
> "Related: note how I approximated a "mobile device height..."

Duh, just now occurred to me that's effectively what `data-esb-viewport-aspect-ratio` is. 
So... `data-esb-viewport-width="768" data-esb-viewport-aspect-ratio="1.3333"` to get **768 x 1024**.

**Comment by kevinmpowell** [comment]
**BLOCKER**
* Need a complete device list so I can implement

For starters:
* iPhone (defaults to iPhone 6)
* iPhone 6
* iPhone 6 Plus
* iPhone 4/4s/5/5s/5c - all the same size but iOS 6, 7 & 8 may have different amounts of browser chrome affecting the viewable area - how deep do we want to go?
* iPad
* iPad Mini

I pulled the following from a "Best Android Phones 2015" List
* LG G4
* Samsung Galaxy Note 4
* Samsung Galaxy S6
* Moto X
* HTC One M9

**Comment by kevinmpowell** [comment]
Nice to Have
![screenshot 2015-06-17 12 07 46](https://cloud.githubusercontent.com/assets/979463/8212428/471bcb7c-14e1-11e5-85ae-17ed3aaea597.png)
