### ISSUE TITLE
Framing Pages with Stenciled Device Containers

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/Blocks#166]
If we establish a convention to specify a device (#165), could we include a stenciled / B&W-like picture of a device behind and bounding around the framed page?

How does that impact default spacing?

Presumably, the stencil would scale with the frame's scale, and also look good at various sizes.

Where would we get the stenciled art?

**Comment by kevinmpowell** [comment]
> Where would we get the stenciled art?

I recommend SVG files to handle the scaling. A quick Google search revealed plenty of options:
http://gaspix.net/2015/04/free-device-frames-vector/

At least for the Apple products...not sure about the others.
