### ISSUE TITLE
Update Component Loader to use "data-esb-" attributes

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#168]
Normalizing with Page Framer. Update wiki examples after modifying source.

Ensure `data-` attributes without `data-esb-` still work for Component Loader (backward compatibility).

**Comment by nathanacurtis** [comment]
Don't forget backward compatibility as much as possible, for now.

On Fri, Jun 12, 2015 at 4:40 PM, Kevin Powell <notifications@github.com>
wrote:

> Normalizing with Page Framer. Update wiki examples after modifying source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EightShapes/Blocks/issues/168>.
>



-- 

*Nathan Curtis*
Principal, EightShapes LLC
nathan@eightshapes.com
@nathanacurtis
703-296-8831

**Comment by kevinmpowell** [comment]
> Don't forget backward compatibility as much as possible, for now.

Thanks, added to the description.
