### ISSUE TITLE
Loader Product Name

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#179]
### Naming Options Under Consideration

* *Load,* current name and internally used term, but an overloaded term and not distinct from the rest of the Blocks toolkit (i.e. they all "load" something).
* *Component* not a verb, also an overloaded term.
* *Unify*: Already used for documentation toolkit that uses the same approach (loading bits from smaller files to create a unified whole)
* *Assemble*
* *Construct*
* *Fabricate*
* *Combine*: Chapter name in my book referring to the combination of the smaller parts into a composed piece.

c/ @nathanacurtis @humancompanion

**Comment by nathanacurtis** [comment]
Adding terms to description as our running set of options to consider:

* *Unify*: Already used for documentation toolkit that uses the same approach (loading bits from smaller files to create a unified whole)
* *Assemble*
* *Construct*
* *Fabricate*
* *Combine*: Chapter name in my book referring to the combination of the smaller parts into a composed piece.

**Comment by kevinmpowell** [comment]
A couple more:
* _Include_
* _Compose_

**Comment by nathanacurtis** [comment]
Just a reminder based on conversation earlier today: @brownorama, add ideas here.

**Comment by brownorama** [comment]
The short, one syllable words are appealing for individual tools in this suite.

In place of **Load** I like these for noun/verb ambiguity:

Slot
Rig < I like this one
Joint
Form
Cast
Mold (sadly, this also has a negative connotation)

Two syllables I think has somewhat more character:

Gather
Collect
Muster < I like this one
Makeup
Fabric < I like this one best of all

**Comment by nathanacurtis** [comment]
Another idea:

Injector

**Comment by nathanacurtis** [comment]
I'm wary of *Include* because of it's historical assumptions (and simplicity, and reality that it never really was good enough for people to use much). It's also the name of a competitive agency in DC (nClud).

**Comment by kevinmpowell** [comment]
I like Injector, but following our "noun" protocol would "Inject" make more sense?

**Comment by kevinmpowell** [comment]
We've landed on **Include** for now, closing this issue.
