### ISSUE TITLE
Frame Component Examples

### ISSUE THREAD

**Issue by nathanacurtis** [EightShapes/Blocks#193]
Source and utilize specific components from Case Studies and Eightshapes.com to illustrate component framing. 

Examples should include:
* Component, Wide, 100% Scaled
* Component, Narrow, 100% Scaled
* Grid of Different Components across page (as if in grid display)
* 3 Up of Same Vertically-oriented Component, 25% Scaled, Revealing Responsiveness
* Stack of Same Horizontally-oriented Component, scaled or not, Revealing Responsiveness

**Comment by nathanacurtis** [comment]
In reviewing case study work thus far, interesting examples from AACT include:

* Project Description
![image](https://cloud.githubusercontent.com/assets/1165904/8377652/fa4596b4-1be0-11e5-8479-4d589c302349.png)
* Sample Findings
![image](https://cloud.githubusercontent.com/assets/1165904/8377659/05b15862-1be1-11e5-941d-3c0d59c9a9c9.png)
* Findings Stack/4 Up
![image](https://cloud.githubusercontent.com/assets/1165904/8377667/13e7d1c2-1be1-11e5-9850-c2482df6f2a0.png)

From  eightshapes.com Home:

* Grid of Headshots
* What We Do (with or separate from How We Do It)

**Comment by kevinmpowell** [comment]
* [ ] Zoom example should be less than 100%
* [ ] Add additional "small multiples" to cropping example
* [ ] Make crop offset examples more subtle
* [ ] Change code highlighter on examples
