### ISSUE TITLE
Layered Preview

### ISSUE THREAD

**Issue by francisrupert** [EightShapes/Blocks#194]
We've manually created a preview like this used on project index, how about letting Blocks generate it with same images used by `data-esb-viewport-device`, e.g. [device_frame_iphone_5.svg](https://github.com/EightShapes/Blocks/blob/master/svg/device_frame_iphone_5.svg)? 

Something like...

```html
<div
  data-esb-preview="representative-page-type.html"
  data-esb-preview-views="desktop,laptop,tablet,phablet,phone"
></div>
```

**Comment by nathanacurtis** [comment]
France,

This is a really interesting idea.

It makes me wonder, however, if it's worth the cost of automating an
attractive arrangement, relative to just having an example where a few are
absolutely positioned stacked together. The algorithm to attractively stack
them may take some thinking tinkering and testing, and what we really need
is a simple way to emulate the arrangement. An example may do.

Feel free to take a stab using the framing we already have, and see if that
works well enough for you.

Nathan



On Sat, Jun 27, 2015 at 8:26 AM, Francis Rupert <notifications@github.com>
wrote:

> We've manually created a preview like this used on project index, how
> about letting Blocks generate it with same images used by
> data-esb-viewport-device, e.g. device_frame_iphone_5.svg
> <https://github.com/EightShapes/Blocks/blob/master/svg/device_frame_iphone_5.svg>?
>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1165933/8391862/bd90b5aa-1c99-11e5-9cbc-7f6e5f99ca11.png>
>
> Something like...
>
> <div
>   data-esb-preview="representative-page-type.html"
>   data-esb-preview-views="desktop,laptop,tablet,phablet,phone"
> ></div>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EightShapes/Blocks/issues/194>.
>



-- 

*Nathan Curtis*
Principal, EightShapes LLC
nathan@eightshapes.com
@nathanacurtis
703-296-8831

**Comment by kevinmpowell** [comment]
Haven't had a need for this yet, closing for now.
