### ISSUE TITLE
Include: nested includes not working

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/Blocks#234]

**Comment by robmaggidev** [comment]
Hello Kevin, do you have any inputs/tips about how to quickly fix this bug? Thanks in advance.

**Comment by kevinmpowell** [comment]
@robmaggidev this should be resolved in the latest release: https://github.com/EightShapes/Blocks/releases/tag/v2.8.0

More docs to come regarding other changes in this release, but the previous syntax should still work. If you have issues let me know and I can help you out.

**Comment by robmaggidev** [comment]
Kevin, you can't imagine how happy I am to hear it! :) 
Many many many thanks! You guys are doing an incredible job!

**Comment by kevinmpowell** [comment]
@robmaggidev thanks! I'd love to see what you're using Blocks for if it's something you could share.
