### ISSUE TITLE
Viewer Template data attr

### ISSUE THREAD

**Issue by francisrupert** [EightShapes/Blocks#94]
**BACKGROUND**: 
The Blocks Viewer currently allows for a single template, via `viewer_template_uri` in the `config.json`. 

**ASK**: 
Would like ability to selectively assign a viewer template from component reference, e.g...

```html
<div
  data-frame-component="thing"
  data-variation="v0"
  data-viewer-template="path/to/alt-viewer-template">
</div>
```

**Comment by kevinmpowell** [comment]
Available as `data-esb-component-frame-template` in latest Frame release: 2.7.3
